// Generated by tools/view-build.mjs from validated Wes view packages.
import assets from "../../.generated/view-assets.json";
import {externalModule} from "./external/module";
import type {ViewAsset} from "./external/document";
export const packagedViews = (assets as unknown as ViewAsset[]).map(externalModule);
