/** Deterministic code generation from the backend's resolved Wes contracts. */
import { generateContract } from "./view-package/contracts.mjs";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packages = JSON.parse(execFileSync("cargo", ["run", "--quiet", "--locked", "-p", "wes-views", "--bin", "wes-view-build"], {cwd:root, encoding:"utf8", maxBuffer:8*1024*1024}));
const files = new Map();
const banner = "// Generated by tools/view-build.mjs from validated Wes view packages.\n";
let modules = banner + 'import assets from "../../.generated/view-assets.json";\nimport {externalModule} from "./external/module";\nimport type {ViewAsset} from "./external/document";\nexport const packagedViews = (assets as unknown as ViewAsset[]).map(externalModule);\n';
packages.forEach(({directory,definition:d}) => {
  const generated = generateContract({...d,artifact:null});
  files.set(path.join(root,"views",directory,"contract.ts"),generated);
});
// Example authoring contracts are build products too. The GUI instance tests consume
// range-summary; regenerate every sample from its editable manifest and type package.
const exampleRoot = path.join(root,"examples/view-packages/source");
for (const directory of fs.readdirSync(exampleRoot,{withFileTypes:true}).filter(entry=>entry.isDirectory()).map(entry=>entry.name).sort()) {
  const example = path.join(exampleRoot,directory);
  const exampleContract = JSON.parse(execFileSync("cargo",["run","--quiet","--locked","-p","wes-views","--bin","wes-view-build","--","--source",example],{cwd:root,encoding:"utf8",maxBuffer:8*1024*1024}));
  files.set(path.join(example,"contract.ts"),generateContract({...exampleContract.definition,artifact:null}));
}
const assets = execFileSync("cargo",["run","--quiet","--locked","-p","wes-views","--bin","wes-view-build","--","--assets"],{cwd:root,encoding:"utf8",maxBuffer:32*1024*1024});
files.set(path.join(root,"gui/.generated/view-assets.json"),JSON.stringify(JSON.parse(assets))+"\n");
files.set(path.join(root,"gui/src/value-views/generated.ts"),modules);
files.set(path.join(root,"gui/src/value-views/catalogue.json"),JSON.stringify(packages.map(p=>p.definition),null,2)+"\n");
for (const [file, content] of files) {
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(file) || fs.readFileSync(file,"utf8")!==content) throw new Error(`Generated view file is stale: ${path.relative(root,file)}`);
  } else if (!fs.existsSync(file) || fs.readFileSync(file,"utf8")!==content) {fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content);}
}
console.log(`${packages.length} view packages ${process.argv.includes("--check")?"verified":"generated"}`);
