//! Explicit distributable sources; no user files or installed node_modules are embedded.
pub(super) const FILES: &[(&str, &str)] = &[
    (
        "package.json",
        include_str!("../../../../tools/view-toolchain/package.json"),
    ),
    (
        "package-lock.json",
        include_str!("../../../../tools/view-toolchain/package-lock.json"),
    ),
    (
        "wes-view-package.mjs",
        include_str!("../../../../tools/view-toolchain/entry.mjs"),
    ),
    (
        "README.md",
        include_str!("../../../../tools/view-toolchain/README.md"),
    ),
    (
        "sdk/package.json",
        include_str!("../../../../packages/view-sdk/package.json"),
    ),
    (
        "sdk/index.ts",
        include_str!("../../../../packages/view-sdk/index.ts"),
    ),
    (
        "sdk/contract.ts",
        include_str!("../../../../packages/view-sdk/contract.ts"),
    ),
    (
        "sdk/values.ts",
        include_str!("../../../../packages/view-sdk/values.ts"),
    ),
    (
        "sdk/time.ts",
        include_str!("../../../../packages/view-sdk/time.ts"),
    ),
    (
        "sdk/geometry.ts",
        include_str!("../../../../packages/view-sdk/geometry.ts"),
    ),
    (
        "sdk/frame.tsx",
        include_str!("../../../../packages/view-sdk/frame.tsx"),
    ),
    (
        "sdk/theme.ts",
        include_str!("../../../../packages/view-sdk/theme.ts"),
    ),
    (
        "sdk/theme.json",
        include_str!("../../../../packages/view-sdk/theme.json"),
    ),
    (
        "sdk/authoring.json",
        include_str!("../../../../packages/view-sdk/authoring.json"),
    ),
    (
        "sdk/LICENSE",
        include_str!("../../../../packages/view-sdk/LICENSE"),
    ),
    (
        "compiler/package.json",
        include_str!("../../../../tools/view-package/package.json"),
    ),
    (
        "compiler/index.mjs",
        include_str!("../../../../tools/view-package/index.mjs"),
    ),
    (
        "compiler/contracts.mjs",
        include_str!("../../../../tools/view-package/contracts.mjs"),
    ),
    (
        "compiler/template/View.tsx",
        include_str!("../../../../tools/view-package/template/View.tsx"),
    ),
    (
        "compiler/template/types.yaml",
        include_str!("../../../../tools/view-package/template/types.yaml"),
    ),
    (
        "compiler/template/view.css",
        include_str!("../../../../tools/view-package/template/view.css"),
    ),
    (
        "compiler/template/view.json",
        include_str!("../../../../tools/view-package/template/view.json"),
    ),
    (
        "compiler/LICENSE",
        include_str!("../../../../tools/view-package/LICENSE"),
    ),
];
